### ISSUE TITLE
Prepare final presentation slides

### ISSUE THREAD

**Issue by IdealChain** [fkleedorfer/aic2014#36]
Should cover the tasks of stage 2, and only be a small part of the presentation (5 minutes).

### Feedback from midterm presentation (our group):

* + Good description of Onion Routing
* + Good Q&A
* - Presentation a little too long (8 minutes).

Very nice solution in general!

### Some hints for the final presentation (general):

* Consider providing a coherent story for your demo
* Dry-run your presentation and demo at least once

**Comment by fkleedorfer** [comment]
Please post in TUWEL: shall  we hold the same presentation, but updated, or should it be different, content-wise?

**Comment by IdealChain** [comment]
Submitted, answer pending.

**Comment by IdealChain** [comment]
### Interesting content ideas

* Weakpoints of our solution (privacy/security wise)
* Comparison to tor
* Possible OR use cases and actors
* Statistics (LOCs, benchmark results)

**Comment by IdealChain** [comment]
https://tuwel.tuwien.ac.at/mod/forum/discuss.php?d=55610
