### ISSUE TITLE
Prepare final demo

### ISSUE THREAD

**Issue by IdealChain** [fkleedorfer/aic2014#38]
Carefully think about how you are actually going to demonstrate your tool, as this will be part of
the grading. You have 20 minutes per presentation (strict), minus the 5 minute powerpoint slides part.

**Comment by IdealChain** [comment]
Basic AIC demo idea:

1. Show EC2 instances
- Show client Web-UI, basic routing
- Show load balancing (bombing)
- Kill two chain nodes
- Show route errors and retries
- Show newly created EC2 chain node instances

**Comment by fkleedorfer** [comment]
Revised:

1. Show EC2 instances in AWS console
2. Show directory node, click on some of the chainnodes, show their gui
3. Show quoteserver web gui
4. Show client Web-UI, basic routing (only 1 request)
5. Kill 1 chainnode in console
6. Kill 1 chainnode through slow ping
7. Show 1 request via web gui (hope for error and retries)
8. Start big bomb (10000)
9. make 1 chainnode return 404
10. make 1 chainnode slow
11. demonstrate that they get avoided
