### ISSUE TITLE
Analyze Performance issues

### ISSUE THREAD

**Issue by fabthe** [fkleedorfer/aic2014#43]
sending messages takes quite some time (even localhost, ~500 - 1000ms).
Investigate "where" this time is lost.

**Comment by IdealChain** [comment]
Guess: a great chunk of the time is lost during the encryption key generation (SecureRandom).

**Comment by fkleedorfer** [comment]
I don't think we have performance issues:
Just bombed the system with 1000 messages (locally), here's the end of the output
```
21:29:40.312		Client:            Success!  (successful: 999, failed: 0, 1 still to go)
21:29:40.333		Client:            Success!  (successful: 1000, failed: 0, 0 still to go)
21:29:40.333		Client: done bombing. Sent 1000 messages in 25,27 seconds (1000 successful, 0 failed, 39,58 messages per second)
```
