### ISSUE TITLE
Register Unregister Nodes

### ISSUE THREAD

**Issue by GertiForsthuber** [fkleedorfer/aic2014#51]
When started the defined nodes are started, when one is shut down its restarted
what is missing is when a new node connects-  this must call the create function in the connector
unregister - question is shall it be automatically restarted? better not so just remove from list in connector and terminate
da reden wir noch drüber - machen wir am besten gemeinsam

**Comment by fabthe** [comment]
Ok, I will do the review for your code.

**Comment by fkleedorfer** [comment]
done
